### ISSUE TITLE
Why the CSI data captured in empty lab should be concatenated with the activity CSI data?

### ISSUE THREAD

**Issue by thinszx** [dmsp123/FallDeFi#2]
Hi, thank you for posting the source code of your project. It helps me a lot.

I'm reading the data processing codes and I find the CSI data captured in empty lab is concatenated with the activity data and they're used together to substrct mean value and center data afterwards. I wonder why the empty lab data is used. Does it help to remove the environment effects from the detection? I didn't find the anwser in paper. Thanks in advance.

**Comment by Yang-JinJiang** [comment]
Did you solve this problem?

**Comment by thinszx** [comment]
> Did you solve this problem?

No, but I believe it should be the reason I guessed XD
